### ISSUE TITLE
Incorrect name for clon #426

### ISSUE THREAD

**Issue by xoan** [brico-labs/RetoADNCloneWars#4]
Clon #426 in http://maytheclonebewithyou.com/index.php/view is named «Anymon», but in the generated list is named «Tesla».

**Comment by MiloBarral** [comment]
Updated in next batch.

**Comment by fuseprods** [comment]
Updated :+1:

**Comment by rafacouto** [comment]
The right one is 'Tesla'. MayTheCloneBeWithYou has recovered the error and now it shows 'Tesla'.
