### ISSUE TITLE
ADN renderizado como imágenes

### ISSUE THREAD

**Issue by CarlosGS** [brico-labs/RetoADNCloneWars#7]
No veo cómo hacer un pull request de esto:
https://github.com/carlosgs/RetoADNCloneWars/tree/gh-pages

¿Podéis crear una rama gh-pages y hacer un pull request para que se vea el ADN? Luego se podrá hacer un pull request sobre dicha rama, y el resultado será la siguiente URL:  
http://brico-labs.github.io/RetoADNCloneWars/flat_render  
(Ahora se puede previsualizar en mi fork http://carlosgs.github.io/RetoADNCloneWars/flat_render )

Así si alguien se curra una visualización 3D con WebGL se podría alojar de la misma rama para que esté en los servidores de GitHub.

**Comment by CarlosGS** [comment]
La verdad es que el método para generarlos es un poco cutre, es necesario ajustar los valores para que las imágenes "casen" unas con otras correctamente... no estoy seguro de si se puede automatizar... :S

**Comment by rafacouto** [comment]
No tenemos rama gh-pages. Debería dejarte hacer el PR desde carlosgs/gh-pages a brico-labs/master. También puedes llevar las modificaciones sobre la rama master (git checkout master && git rebase gh-pages) y luego hacer PR. 

Prueba y nos dices...

**Comment by rafacouto** [comment]
Para que casen [sobre la hélice](https://github.com/brico-labs/RetoADNCloneWars/blob/master/src/sequence.scad) haría falta rotar cada par sobre su centro los grados justos en X e Y así como reducir la variable gap para que encajen. Si te animas... ;)

**Comment by CarlosGS** [comment]
La rama gh-pages es la que necesita github para generar la web, si hago el
pull request a master no funcionará :-S

Luego intento generar la cadena en espiral

**Comment by rafacouto** [comment]
Ah! También se puede acceder al contenido "raw" desde raw.githubusercontent.com sin tener que usar Jekyll.

Como ejemplo, echa un vistazo al [README.md del generador](https://github.com/brico-labs/RetoADNCloneWars/blob/master/src/README.md).

**Comment by CarlosGS** [comment]
Claro, pero si abres un html te lo imprime por pantalla sin renderizarlo:
https://raw.githubusercontent.com/carlosgs/RetoADNCloneWars/gh-pages/flat_render/ADN_even.html

**Comment by CarlosGS** [comment]
Aun así, no estoy usando Jekyll, simplemente uso la rama gh-pages como raíz de la carpeta http://carlosgs.github.io/RetoADNCloneWars/

**Comment by rafacouto** [comment]
Okis! Rama creada ;)

**Comment by CarlosGS** [comment]
Gracias!! ^_^
